services:
  postgres:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: chat_app
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatdb
      SPRING_DATASOURCE_USERNAME: chatuser
      SPRING_DATASOURCE_PASSWORD: chatpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8081:8081"

  worker:
    build:
      context: ./python-worker
    container_name: chat_worker
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379


volumes:
  postgres-data:
